---
- hosts: all 
  become: true 
  tasks:
  - name: install apache  
    apt:
      name:
        - apache2   
      update_cache: yes
  - name: chmod Var
    file:
      path: /var
      mode: '0777'
  # - name: suppression index.html
  #   file:
  #     path: /var/www/html/index.html
  #     state: absent
  - name: pokemon-index copy
    copy: 
      src: html/
      dest: /var/www/html
  - name: demarrage appache
    service:
      name: apache2
      state: started 
      enabled: yes
